### ISSUE TITLE
Shoold I need to RecordEvent asyn?

### ISSUE THREAD

**Issue by AlanDan** [Countly/countly-sdk-cordova#10]
I found a problem recently on my android device Nexus-5, my app  be came lagging and slow , or even blocked at least 3 seconds. all of these happened just when a RecordEvent method had been invoked. I'm sure of this because when I stopped running RecordEvent, everything became right. It runs nicely till our server of Countly-Service has been stopped for a long while for some reasons. Then I found that the SDK of android is using SharePreference file to cache Event-Data,  and this file started becoming larger, like 600kb+. meanwhile my app started to be very slow and lagging, even blocked for a while. So I checked all data of this file and found a very huge 'string' label or element inside of it. I think this might not be a good design for data cache, So my question is how can I prevent this happening again or I  just need to run RecordEvent asynchronously every time?

**Comment by trinisofttechnologies** [comment]
@AlanDan, @iartem There are 2 alternatives from here.
1. Is to use the countly web sdk, instead of using, countly phonegap sdk. As, it is using native android java code, and that is common for all.
2. would be @iartem look at this concern and fix the string cache issue in android java code, or provide a suggestion on the same. 

Thanks

**Comment by iartem** [comment]
Hi Guys,

New, largely refactored Android SDK is already on the way. It doesn't block at all and removes lots of synchronizations while still using SharedPreferences inside. So it'll be substantially faster even in this case. 

I'd welcome any suggestions for how to store Countly information efficiently while not using SharedPreferences. The thing is, we went off sqlite some years ago because it was a major overhead for our tiny SDK and because of lots of exceptions we were getting out of it.

In any case, 600Kb+ of something in SharedPreferences is of course a bad use case. Why there is so much data?

**Comment by AlanDan** [comment]
@trinisofttechnologies @iartem Thanks for your replies.
@iartem  By far we've found only one case on one device. For now our app are running on over 200,000 devices, and this kind of issue is rarely reported. Seems like it only occurred on my test device.  Through the describe of my question above, as you know our Countly-Sevices Server had crashed for a long while, I guess my test phone cached too much data during that time.

**Comment by trinisofttechnologies** [comment]
@iartem 

If the new sdk is all async, then you may close this issue,

as per the latest version, the sdk is synced with the latest work done on android sdk.

Thanks
