### ISSUE TITLE
Rich push notifications not working on Cordova

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-cordova#23]
Rich push notifications tested on HTC One M8, Samsung Galaxy S6, LG G5 and iPhone 6S devices – same result.

**Comment by rajeshyandamuri** [comment]
Hi Gorkem,

Regular notifications also not working for us. We have integrated Native iOS SDK and its working fine. While we use it in Cordova ionic project(Android + iOS) the general push also not working. Please share us any step by step provess to integrate in mobile cross platform (Angular + ionic).

Thanks in advance.

**Comment by trinisofttechnologies** [comment]
This is the same issues as this one

https://community.count.ly/t/ionic2-couldnot-install-sdk-for-android/294/18


https://community.count.ly/t/push-notifications-angular-application-for-ios-android/301

All these will be counted as one issue.

**Comment by trinisofttechnologies** [comment]
Please install this plugin  https://github.com/phonegap/phonegap-plugin-push

and make sure you are able to register your device and get a push token

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonregistration-callback

Use this method to verify you are able to get push device token.

If you are able to get the push device token then countly sdk can just send that push device token to the countly server.

Let me know how it goes, so that I can assists you on the next updates.

Thanks

**Comment by gorkem-cetin** [comment]
As a side note, rich push notifications work on Android but not on iOS (due to framework used).

**Comment by anilo** [comment]
Any update on rich push notification on iOS?

**Comment by gorkem-cetin** [comment]
Unfortunately the 3rd party library we used for this purpose doesn't yet support rich push notifications for iOS, hence we don't support. We are always keeping an eye and as soon as this feature is released, we will implement.
