### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by deliriousrhino** [Countly/countly-sdk-cordova#5]
I have added the plugin from
https://github.com/nicolsondsouza/countly-sdk-js

However on iOS I now get the error 
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot create an NSPersistentStoreCoordinator with a nil model'

Thrown from CountlyDB.h on line 226
  s_persistentStoreCoordinator = [[NSPersistentStoreCoordinator alloc] initWithManagedObjectModel:[self managedObjectModel]]; 

This is how I am calling the code in javascript
if (window.CountlyCordova) {
            //initialize
            CountlyCordova.init(this.countlyServer, this.key);
            var event = {
                "eventName": "mypaymentevent",
                "eventCount": 1
            };
            CountlyCordova.sendEvent(event);
        }

**Comment by nicolsondsouza** [comment]
ok, working on it.

**Comment by nicolsondsouza** [comment]
@deliriousrhino

I tested on ios device iPhone 5, 
and it worked for me,

you might haven't added this

Go to /src/ios/sdk/Countly.xcdatamodeld 
drag and drop Countly.xcdatamodeld in your plugin folder.
(because cordova plugin doesn't support folder, so has to be added manually.)

I got the same error,

closing this issue.

**Comment by deliriousrhino** [comment]
Thanks @nicolsondsouza This was the case
